package com.example

enum class VisualMode(val title: String) {
    WAVEFORM("Waveform"),
    SPECTRUM("RF Spectrum"),
    WATERFALL_3D("3D Waterfall"),
    SDR_WATERFALL("SDR Waterfall"),
    IQ_PLOT("I/Q Plot"),
    RADAR_SPECTRUM("Radar Plot"),
    PHASE_SPACE("Phase Space"),
    LISSAJOUS("Lissajous"),
    PARTICLE_SPECTRUM("Particle Spectrum"),
    NEON_RINGS("Neon Rings"),
    MATRIX_RAIN("Matrix Rain"),
    STARFIELD_WARP("Starfield"),
    VINYL_GROOVE("Vinyl"),
    LIQUID_BLOB("Liquid Blob"),
    SOUND_RINGS("Sound Rings"),
    FIREWORKS("Fireworks"),
    HEXAGON_GRID("Hex Grid"),
    MANDALA("Mandala"),
    PULSE_HEART("Pulse Heart"),
    DNA_HELIX("DNA Helix"),
    ELECTRIC_ARC("Electric Arc"),
    FOUNTAIN("Fountain"),
    GUITAR_STRINGS("Strings"),
    AUDIO_ORB("Audio Orb"),
}
